freelance_backend/drkiq/config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: %i[create show]
  resources :chat_messages, only: %i[create]
  resources :jobs, only: %i[index show]
  resources :job_applications, only: %i[create]
  resources :user_profiles

  post 'login' => 'users#login'
  resources :users
  # get 'pages/home'
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

freelance_backend/drkiq/app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

freelance_backend/drkiq/app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: %i[ show edit update destroy ]

  # GET /user_profiles or /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1 or /user_profiles/1.json
  def show
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles or /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to user_profile_url(@user_profile), notice: "User profile was successfully created." }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1 or /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to user_profile_url(@user_profile), notice: "User profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1 or /user_profiles/1.json
  def destroy
    @user_profile.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: "User profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :about, :experiences, :skills, :pricing, :social_links)
    end
end

freelance_backend/drkiq/app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

freelance_backend/drkiq/app/views/user_profiles/_form.html.erb
<%= form_with(model: user_profile) do |form| %>
  <% if user_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
        <% user_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_area :about %>
  </div>

  <div>
    <%= form.label :experiences, style: "display: block" %>
    <%= form.text_field :experiences %>
  </div>

  <div>
    <%= form.label :skills, style: "display: block" %>
    <%= form.text_field :skills %>
  </div>

  <div>
    <%= form.label :pricing, style: "display: block" %>
    <%= form.text_field :pricing %>
  </div>

  <div>
    <%= form.label :social_links, style: "display: block" %>
    <%= form.text_field :social_links %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

freelance_backend/drkiq/app/views/user_profiles/_user_profile.html.erb
<div id="<%= dom_id user_profile %>">
  <p>
    <strong>User:</strong>
    <%= user_profile.user_id %>
  </p>

  <p>
    <strong>About:</strong>
    <%= user_profile.about %>
  </p>

  <p>
    <strong>Experiences:</strong>
    <%= user_profile.experiences %>
  </p>

  <p>
    <strong>Skills:</strong>
    <%= user_profile.skills %>
  </p>

  <p>
    <strong>Pricing:</strong>
    <%= user_profile.pricing %>
  </p>

  <p>
    <strong>Social links:</strong>
    <%= user_profile.social_links %>
  </p>

</div>

freelance_backend/drkiq/app/views/user_profiles/edit.html.erb
<h1>Editing user profile</h1>

<%= render "form", user_profile: @user_profile %>

<br>

<div>
  <%= link_to "Show this user profile", @user_profile %> |
  <%= link_to "Back to user profiles", user_profiles_path %>
</div>

freelance_backend/drkiq/app/views/user_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User profiles</h1>

<div id="user_profiles">
  <% @user_profiles.each do |user_profile| %>
    <%= render user_profile %>
    <p>
      <%= link_to "Show this user profile", user_profile %>
    </p>
  <% end %>
</div>

<%= link_to "New user profile", new_user_profile_path %>

freelance_backend/drkiq/app/views/user_profiles/new.html.erb
<h1>New user profile</h1>

<%= render "form", user_profile: @user_profile %>

<br>

<div>
  <%= link_to "Back to user profiles", user_profiles_path %>
</div>

freelance_backend/drkiq/app/views/user_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_profile %>

<div>
  <%= link_to "Edit this user profile", edit_user_profile_path(@user_profile) %> |
  <%= link_to "Back to user profiles", user_profiles_path %>

  <%= button_to "Destroy this user profile", @user_profile, method: :delete %>
</div>