freelance_backend/drkiq/config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: %i[create show]
  resources :chat_messages, only: %i[create]
  resources :jobs, only: %i[index show]
  resources :job_applications, only: %i[create]
  resources :user_profiles

  post 'login' => 'users#login'
  resources :users
  # get 'pages/home'
  root 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

freelance_backend/drkiq/app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :job
  belongs_to :client, foreign_key: :client_id, class_name: 'User', optional: true
  belongs_to :freelancer, foreign_key: :freelancer_id, class_name: 'User', optional: true
  has_many :chat_messages, -> { order(:created_at) }
end

freelance_backend/drkiq/app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[show]

  # # GET /chats or /chats.json
  # def index
  #   @chats = Chat.all
  # end

  # GET /chats/1 or /chats/1.json
  def show
    respond_to do |format|
      format.json { render :show, status: :ok }
    end
  end

  # # GET /chats/new
  # def new
  #   @chat = Chat.new
  # end

  # # GET /chats/1/edit
  # def edit
  # end

  # POST /chats or /chats.json
  def create
    @chat = Chat.new(chat_params)
    @job = Job.find_by(id: chat_params[:job_id])

    if @current_user.client?
      @chat.client_id = @current_user.id
      @chat.freelancer_id = chat_params[:freelancer_id]
    else
      @chat.client_id = @job.client_id
      @chat.freelancer_id = @current_user.id
    end

    respond_to do |format|
      if @chat.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /chats/1 or /chats/1.json
  # def update
  #   respond_to do |format|
  #     if @chat.update(chat_params)
  #       format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
  #       format.json { render :show, status: :ok, location: @chat }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @chat.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /chats/1 or /chats/1.json
  # def destroy
  #   @chat.destroy

  #   respond_to do |format|
  #     format.html { redirect_to chats_url, notice: "Chat was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chat
    @chat = Chat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def chat_params
    params.require(:chat).require(:job_id)
    if @current_user.client?
      params.require(:chat).permit(:job_id, :freelancer_id)
    else
      params.require(:chat).permit(:job_id)
    end
  end
end

freelance_backend/drkiq/app/helpers/chats_helper.rb
module ChatsHelper
end

freelance_backend/drkiq/app/views/chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Freelancer:</strong>
    <%= chat.freelancer_id %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= chat.client_id %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= chat.job_id %>
  </p>

</div>

freelance_backend/drkiq/app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :freelancer_id, style: "display: block" %>
    <%= form.number_field :freelancer_id %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.number_field :client_id %>
  </div>

  <div>
    <%= form.label :job_id, style: "display: block" %>
    <%= form.number_field :job_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

freelance_backend/drkiq/app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

freelance_backend/drkiq/app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chats</h1>

<div id="chats">
  <% @chats.each do |chat| %>
    <%= render chat %>
    <p>
      <%= link_to "Show this chat", chat %>
    </p>
  <% end %>
</div>

<%= link_to "New chat", new_chat_path %>

freelance_backend/drkiq/app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path %>
</div>

freelance_backend/drkiq/app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chat %>

<div>
  <%= link_to "Edit this chat", edit_chat_path(@chat) %> |
  <%= link_to "Back to chats", chats_path %>

  <%= button_to "Destroy this chat", @chat, method: :delete %>
</div>